### ISSUE TITLE
Demo data does not define a subject tree

### ISSUE THREAD

**Issue by LaurieHeer** [MicrosoftLearning/MB-210-Dynamics365forSales#3]
# Module: 3
#### Step: 5

The sample data does not have any subjects defined, so the student will not be able to expand the query and select anything other than "default subject". Additional subjects can be added via the soon to be deprecated Advanced Settings. I did try to add the Subject entity to the Site Map, but it did not display. Please advise whether or not Sales Enterprise should have access to this functionality and the best way to configure it.

**Comment by anjenni** [comment]
Thanks Laurie, followed your lead and merged your pull request to remove instruction around Subject.
