### ISSUE TITLE
MB-210 Lab Environment for Students does not work

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/MB-210-Dynamics365forSales#8]
# Module: All
#### Step: All

Description of issue

I tried to teach this course today. While the slides are fine, spars but fine for a one-day event. 

The Lab Environment and Labs however are simply not acceptable quality and simply don't work. I also ran into issues with the LODS environment where the assigned students could not even access the Lab Instructions on the Instructions tab of the LODS interface. 

0. None of the students could access the LODS Lab Instructions. Screen image is attached. 

1. The shared environment provided is so polluted with leftovers from other courses that ran in other MB-210 course events left over. The concept of trying to save money by having many course events share the same lab environment is simply not working. Please dedicate one environment to each class so that students do see data from other courses. Trying to teach a course with the environment the way it is not working, its confusing, and it does not give a very good impression of the Microsoft product. 

2. 10 of the 12 students did not have access to the Sales Hub icon within the Office menu of applications so I had to get them there to open the Environment via the PowerPlatform Admin Portal. 

3. Within the Sales Hub the students had various degrees of access with some having menu items displayed and some not. 

4. The labs that we could do were challenging because of all of the leftover Accounts and Contacts that have similar names because there are many people in the world that have similar First Name and Last Name initials. This created additional steps not outlined in the lab manual.  

5. The Sales Hub Dashboard did not work for me or anyone. In fact, mine came up as MEIN DASHBOARD with a German title but with an error on presenting the dashboard so I could not demo anything.  

And the list goes on. I have delivered many MOC courses over the years but I was really disappointed with the lack of quality control on this one for the way Microsoft deploys the Dynamics Environment for the Sales Hub course event and then significant testing of the labs as presented on the LODS environment. 

Thank you for your consideration and attention to this issue. 

![LODS lab instructions not accessible second student](https://user-images.githubusercontent.com/1082625/152905660-2c81a68f-971f-44cc-b41e-a5b697b2aa9e.png)
![MB-210 LODS Instructions not available](https://user-images.githubusercontent.com/1082625/152907324-011628fc-1156-45d4-9ef0-b7a00da22b64.jpg)
![LODS lab instructions not accessible](https://user-images.githubusercontent.com/1082625/152907346-06fab7c7-6e18-4ebf-ab02-e2ecbba8b4c8.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by anjenni** [comment]
Hi @arnoldvilleneuve! So sorry you had this experience. Wanted to provide an update that we're working with our lab provisioner to fix those issues in recycling. Thanks so much for your thorough comment, it really helps us when we are raising these issues with the provisioning service.

**Comment by arnoldvilleneuve** [comment]
Thanks for letting me know. The event was an absolute disaster. We lost a client because of the poor quality of this course! 
Arnold Villeneuve 613-833-0984 

    On Wednesday, March 30, 2022, 04:06:23 p.m. EDT, Anna Jennings ***@***.***> wrote:  
 
 


Hi @arnoldvilleneuve! So sorry you had this experience. Wanted to provide an update that we're working with our lab provisioner to fix those issues in recycling. Thanks so much for your thorough comment, it really helps us when we are raising these issues with the provisioning service.

**Comment by RobertRybaric** [comment]
Hi Anna and all, I can confirm, that the courses are still sub-optimal, the quality of the slides is poor, very basic and not updated and the ALH hosted environment, specifically for courses with one single classroom-wide environment is a pure disaster. That’s why I am using for those courses (MB-210, 220, 230, 240, 910 and PL-600) rather my own environment, where I can prepare everything and there is no danger, that some stupid procedure deletes the environment after I have invested all the preparation time – not kidding, this is how it works at GoDeply for example. So generally my level of satisfaction of the whole package is very low.

Regards, Robert

**Comment by arnoldvilleneuve** [comment]
Agreed.

As MCTs we strive to deliver a great learning experience. To do so we need quality content, solid lab environments, and labs that work.

I sincerely hope the people responsible for producing MOC courses take it more responsibly.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
